//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Side
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentReservation
    {
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int ApartmentId { get; set; }
        public string Details { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPhone { get; set; }
        public string UserAddress { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
