//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Side
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaggedApartment
    {
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public int ApartmentId { get; set; }
        public int TagId { get; set; }
    
        public virtual Apartment Apartment { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
